name: Run Appium Android Tests

on: [push]

jobs:
  appium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java (Required for Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js (Required for Appium)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Required Android Packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "system-images;android-34;default;x86_64" "emulator"
          sdkmanager --licenses

      - name: Clone AVD Setup Script Repository
        run: |
          git clone https://github.com/maiz-an/AVD-Setup-without-Andriod-Studio.git avd-setup
          ls -la avd-setup

      - name: Create Android Virtual Device (Using AVD-Setup Script)
        run: |
          # Navigate into the cloned repository
          cd avd-setup
          # Run the provided script; adjust parameters as needed.
          # For example, if the repository provides a script called create_avd.sh, run:
          chmod +x create_avd.sh
          ./create_avd.sh -n test -a x86_64 -p "android-34" -d "pixel_4"
          # You can list created AVDs to verify:
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Start Android Emulator
        run: |
          echo "Starting Android emulator..."
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -no-boot-anim -gpu off &
          sleep 90  # Wait for emulator to boot
          adb devices

      - name: Install & Start Appium Server
        run: |
          npm install -g appium
          appium --version
          nohup appium --base-path /wd/hub --port 4723 & 
          sleep 10

      - name: Install Appium UIAutomator2 Driver
        run: |
          appium driver install uiautomator2
          appium driver list --installed

      - name: Run Appium Tests
        run: |
          adb devices  # Confirm emulator is detected
          dotnet test --logger "trx;LogFileName=TestResults.trx"
          if [ $? -ne 0 ]; then
            echo "Tests failed, stopping pipeline."
            exit 1
          fi

  
