name: try appium run

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest  # ✅ Switch to macOS for hardware acceleration
    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore AppiumPractise/AppiumPractise.csproj
      
      - name: Build project
        run: dotnet build AppiumPractise/AppiumPractise.csproj --configuration Release
      
      - name: Install Android SDK
        run: |
          brew install --cask android-commandlinetools
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          sdkmanager --install "platform-tools" \
          "platforms;android-35" \
          "system-images;android-35;google_apis_playstore;x86_64" \
          "emulator"
          yes | sdkmanager --licenses
          echo "no" | avdmanager create avd -n test_avd -k "system-images;android-35;google_apis_playstore;x86_64" --device "pixel"

      - name: Start Android Emulator
        run: |
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
          emulator -list-avds
          nohup emulator -avd test_avd -no-audio -no-window -gpu host -no-boot-anim &
          adb wait-for-device
          bootCompleted=""
          while [ -z "$bootCompleted" ] || [ "$bootCompleted" -ne "1" ]; do
            sleep 5
            bootCompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Emulator boot status: $bootCompleted"
          done
          echo "Emulator boot completed!"
          adb devices

      - name: Run Appium tests
        run: dotnet test AppiumPractise/AppiumPractise.csproj --logger trx
