name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - master


jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: pull the project in to the runner
        uses: actions/checkout@v4

      - name: setup appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &

  #    - name: run appium android tests
   #     uses: reactivecircus/android-emulator-runner@v2
     #   with:
      #    api-level: 29
       #   script: ./gradlew connectedCheck

       
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x' # Use the appropriate .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Run Appium Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
