name: Appium CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # Use macOS for better emulator support
    strategy:
      matrix:
        api-level: [35] # Updated to match API level 35

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Required for Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Set up Node.js (Required for Appium)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Required Android Packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-${{ matrix.api-level }}" "system-images;android-${{ matrix.api-level }};google_apis_playstore;x86_64" "emulator"
          sdkmanager --licenses

      - name: Ensure ADB is in PATH
        run: |
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          adb version

      - name: Create & Start Android Emulator
        run: |
          echo "Creating and starting Android emulator..."
          echo "no" | avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis_playstore;x86_64" --device "pixel"
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -no-boot-anim -gpu off &
          sleep 90 # Increased sleep time for better booting
          adb wait-for-device
          adb devices

      - name: Wait for Emulator to Fully Boot
        run: |
          boot_completed=false
          while [ "$boot_completed" != "1" ]; do
            echo "Waiting for emulator to boot..."
            sleep 10
            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
          done
          echo "Emulator is ready!"

      - name: Install & Start Appium Server
        run: |
          npm install -g appium
          appium --version
          nohup appium &

      - name: Install Appium UIAutomator2 Driver
        run: appium driver install uiautomator2

      - name: Run Appium Tests
        run: |
          adb devices
          dotnet test --logger "trx;LogFileName=TestResults.trx"
          if [ $? -ne 0 ]; then
            echo "Tests failed, stopping pipeline."
            exit 1
          fi
