name: Run Appium Tests on Android Emulator

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'  # Adjust to match your C# project version

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Required for Appium

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Appium
      run: npm install -g appium

    - name: Install Appium Doctor
      run: npm install -g appium-doctor

    - name: Install UIAutomator2 Driver for Appium
      run: appium driver install uiautomator2

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3  # Installs Android SDK & tools
      
    - name: Install Android SDK Platform Tools
      run: |
        sdkmanager --install "platform-tools" "platforms;android-35" "system-images;android-35;google_apis;x86_64"

    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses
