name: try appium run

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore AppiumPractise/AppiumPractise.csproj
      
      - name: Build project
        run: dotnet build AppiumPractise/AppiumPractise.csproj --configuration Release

      - name: Start Android Emulator (Cold Boot)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          disable-animations: true
          emulator-options: "-no-snapshot-save -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect"

      - name: Wait for Emulator to Boot
        run: |
          echo "Waiting for emulator to boot..."
          bootCompleted=""
          while [ -z "$bootCompleted" ] || [ "$bootCompleted" -ne "1" ]; do
            sleep 5
            bootCompleted=$(adb shell getprop sys.boot_completed | tr -d '\r')
            echo "Emulator boot status: $bootCompleted"
          done
          echo "Emulator boot completed!"

      - name: Restart ADB Server
        run: |
          adb kill-server
          sleep 3
          adb start-server
          sleep 3
          adb devices

      - name: Retry ADB Connection if Offline
        run: |
          retries=5
          while [ $retries -gt 0 ]; do
            status=$(adb devices | grep "emulator" | awk '{print $2}')
            if [ "$status" == "device" ]; then
              echo "Emulator is online!"
              exit 0
            fi
            echo "Emulator still offline... Retrying in 5s"
            adb kill-server
            adb start-server
            sleep 5
            retries=$((retries - 1))
          done
          echo "Emulator is still offline after retries. Exiting..."
          exit 1

      - name: List Connected Devices
        run: adb devices

      - name: Install APK Inside Emulator
        run: |
          adb install path/to/your.apk
        continue-on-error: true  # In case the APK is already installed

      - name: Launch App Before Running Tests
        run: |
          adb shell am start -n "com.your.app/.MainActivity"

      - name: Run Appium tests
        run: dotnet test AppiumPractise/AppiumPractise.csproj --logger trx
