name: try appium run

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore AppiumPractise/AppiumPractise.csproj
      
      - name: Build project
        run: dotnet build AppiumPractise/AppiumPractise.csproj --configuration Release

      - name: Start Android Emulator (Prebuilt)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect"
          script: adb shell getprop sys.boot_completed

      - name: List Connected Devices
        run: adb devices
      
      - name: Run Appium tests
        run: dotnet test AppiumPractise/AppiumPractise.csproj --logger trx

