name: Run Appium Android Tests

on:
  push:
  workflow_dispatch:

jobs:
  appium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java (Required for Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js (Required for Appium)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Required Android Packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "system-images;android-34;default;x86_64" "emulator"
          sdkmanager --licenses

      - name: Create AVD
        run: |
          echo "Creating Android Emulator..."
          avdmanager create avd -n test -k "system-images;android-34;default;x86_64" --device "pixel_4" --force
          echo "Checking if AVD directory exists..."
          ls -la ~/.android/avd/
          ls -la ~/.android/avd/test.avd/

      - name: Modify AVD Configuration (Fix config.ini error)
        run: |
          if [ -d ~/.android/avd/test.avd ]; then
            echo "hw.lcd.density=320" >> ~/.android/avd/test.avd/config.ini
          else
            echo "AVD directory does not exist! Emulator creation failed."
            exit 1
          fi

      - name: Start Android Emulator
        run: |
          echo "Starting Android emulator..."
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -no-boot-anim -gpu off &
          sleep 60  # Wait for emulator to boot
          adb devices

      - name: Install & Start Appium Server
        run: |
          npm install -g appium
          appium --version
          nohup appium &  # Start Appium in the background

      - name: Install Appium UIAutomator2 Driver
        run: appium driver install uiautomator2

      - name: Run Appium Tests
        run: |
          adb devices  # Confirm emulator is detected
          dotnet test --logger "trx;LogFileName=TestResults.trx"
          if [ $? -ne 0 ]; then
            echo "Tests failed, stopping pipeline."
            exit 1
          fi
