name: Run Appium Tests

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y android-sdk adb
          echo "Dependencies Installed"

      - name: Start Android Emulator
        run: |
          sdkmanager --install "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"
          emulator -avd test -no-window -noaudio -no-boot-anim &
          adb wait-for-device
          echo "Emulator Started"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Appium Tests
        run: dotnet test --no-build
