name: Run Appium Tests

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest  # Change to `ubuntu-latest` if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Appium and Dependencies
        run: |
          cd Appium-practise  # Navigate to the correct folder
          npm install -g appium
          appium -v
          if [ -f package.json ]; then npm install; else echo "No package.json found, skipping install"; fi 

      - name: Install Android SDK and Emulator
        run: |
          choco install android-sdk -y
          echo "y" | sdkmanager --install "system-images;android-30;default;x86_64"
          echo "no" | avdmanager create avd -n test_avd -k "system-images;android-30;default;x86_64"
    
      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator.exe -avd test_avd -noaudio -no-boot-anim -gpu swiftshader_indirect &
          adb wait-for-device

      - name: Verify Emulator is Running
        run: adb devices

      - name: Run Appium Server
        run: appium --log appium.log &

      - name: Run Appium Tests
        run: npm test  # Modify if using a different test command
