name: Run Appium Android Tests

on: [push]

jobs:
  appium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java (Required for Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js (Required for Appium)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Required Android Packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-30" "system-images;android-30;default;x86_64" "emulator"
          sdkmanager --licenses

      - name: Start Android Emulator (If needed)
        run: |
          echo "Starting Android emulator..."
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-snapshot -no-window -no-audio -no-boot-anim -gpu off &
          sleep 60 # Wait for emulator to boot
          adb devices

      - name: Install & Start Appium Server
        run: |
          npm install -g appium
          appium --version
          nohup appium & # Start Appium in the background

      - name: Run Appium Tests
        run: |
          cd appium-tests  # Change directory to where pom.xml exists
          mvn test

