name: Android CI Setup

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Change if using a different distribution
          java-version: '24'

      - name: Verify Java Version
        run: java -version

      - name: Set up Android SDK Environment Variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK Command Line Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools.zip

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android System Image
        run: |
          sdkmanager --install "system-images;android-30;default;x86"

      - name: Verify SDK Manager
        run: sdkmanager --version
