name: Run Appium Tests

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install Android SDK & Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          yes | sdkmanager --install "platforms;android-30" "system-images;android-30;google_apis;x86_64" "platform-tools" "emulator"
          yes | sdkmanager --licenses
          avdmanager create avd -n testEmulator -k "system-images;android-30;google_apis;x86_64" --device "pixel_4"

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -noaudio -no-boot-anim -gpu swiftshader_indirect &
          sleep 60

      - name: Restart ADB Server
        run: |
          adb kill-server
          adb start-server
          adb wait-for-device

      - name: Check Emulator Logs
        run: adb logcat -d > emulator_log.txt

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Run Appium Tests
        run: dotnet test --no-build
