
name: Run Appium Tests

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Appium and Restore Dependencies
        run: |
          npm ci
          npm install -g appium  
          appium -v  

      #  Install Android SDK and Command Line Tools Manually
      - name: Install Android SDK and Command Line Tools
        run: |
          choco install android-sdk -y
          mkdir -p C:\Android\cmdline-tools\latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip
          tar -xvf sdk-tools.zip -C C:\Android\cmdline-tools\latest
          
          
          echo "ANDROID_HOME=C:\Android" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=C:\Android" >> $GITHUB_ENV
          echo "PATH=C:\Android\cmdline-tools\latest\bin;C:\Android\platform-tools;C:\Android\emulator;$PATH" >> $GITHUB_ENV

      # Reload Environment Variables
      - name: Reload Environment Variables
        shell: bash
        run: source $GITHUB_ENV

      # Install Android System Image (Now sdkmanager should work!)
      - name: Install Android System Image
        run: |
          yes | C:\Android\cmdline-tools\latest\bin\sdkmanager --install "system-images;android-30;default;x86"

    
      - name: Create Android Emulator
        run: |
          avdmanager create avd -n test_avd -k "system-images;android-30;default;x86" --device "pixel_3"

      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator.exe -avd test_avd -noaudio -no-boot-anim -gpu swiftshader_indirect &
          adb wait-for-device

      - name: Verify Emulator is Running
        run: adb devices

      - name: Install APK on Emulator
        run: adb install app/MyApp.apk  # Ensure the APK file exists in your repo

      - name: Run Appium Server
        run: appium --log appium.log &

      - name: Run Appium Tests
        run: npm test  # Modify if using a different test command
