
name: Run Appium C# Tests with Android Emulator

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu works best for Android Emulator

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x  # Change this based on your project

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create & Start Android Emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-30;google_apis;x86_64"
          echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-30;google_apis;x86_64" --device "pixel_4"
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect &

      - name: Wait for Emulator to Start
        run: |
          adb wait-for-device
          adb devices

      - name: Install Appium
        run: npm install -g appium

      - name: Start Appium Server
        run: appium --base-path /wd/hub --log-level info &

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Run Appium C# Tests
        run: dotnet test --no-build
